account/urls.py
from django.urls import path

from . import views


app_name = 'account'


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
]

core/urls.py
from django.urls import path

from . import views


app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

pizarra/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path

from . import views


app_name = 'project'


urlpatterns = [
    path('', views.projects, name='projects'),
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.project, name='project'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
    path('<uuid:project_id>/files/upload/', views.upload_file, name='upload_file'),
    path('<uuid:project_id>/files/<uuid:pk>/delete/', views.delete_file, name='delete_file'),
    path('<uuid:project_id>/notes/add/', views.add_note, name='add_note'),
    path('<uuid:project_id>/notes/<uuid:pk>/', views.note_detail, name='note_detail'),
    path('<uuid:project_id>/notes/<uuid:pk>/edit/', views.note_edit, name='note_edit'),
    path('<uuid:project_id>/notes/<uuid:pk>/delete/', views.note_delete, name='note_delete'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')


def about(request):
    return render(request, 'core/about.html')

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="text-3xl">About</h1>

    <div class="mt-6 space-y-6">
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis natus tempore, non in ex beatae eligendi numquam quod alias error nemo optio quidem asperiores molestiae commodi laborum totam similique! Quo.
        </p>

        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis natus tempore, non in ex beatae eligendi numquam quod alias error nemo optio quidem asperiores molestiae commodi laborum totam similique! Quo.
        </p>
    </div>
{% endblock %}

core/templates/core/base.html
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
    </head>

    <body>
        <nav class="py-6 px-8 flex items-center justify-between bg-slate-800">
            <h1 class="text-xl text-white"><a href="{% url 'core:index' %}">Pizarra</a></h1>

            <div class="space-x-4">
                <a href="{% url 'core:about' %}" class="text-white">About</a>

                {% if request.user.is_authenticated %}
                <a href="{% url 'project:projects' %}" class="py-4 px-8 bg-sky-600 text-white">Projects</a>
                {% else %}
                    <a href="{% url 'account:login' %}" class="py-4 px-8 bg-slate-600 text-white">Log in</a>
                    <a href="{% url 'account:signup' %}" class="py-4 px-8 bg-sky-600 text-white">Sign up</a>
                {% endif %}
            </div>
        </nav>

        <main class="py-6 px-8">
            {% block content %}
            {% endblock %}
        </main>

        <footer class="py-8 px-8 bg-slate-900 text-center">
            <p class="text-white">Copyright (c) 2023 - Code With Stein</p>
        </footer>
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
    <header class="py-12 text-center bg-slate-200">
        <h1 class="text-3xl">Welcome to Pizarra</h1>
    </header>
{% endblock %}